# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 816f325ca2f453543b118b2a934e5749ed12ad652f79fc0b6ec3e3e677cffc0a1f5ebb387d456672982d307c28f29e4085b2cff6464dc9170ba35f3fd2846b7b

test:
  secret_key_base: 1ceb60c95c9cc4ee6920956e36c10f69e70c59cdf06bad4d108006ff8acbdf7c7a9538d9d763b420a7e70f64b5c043ca7389c1187aacde8db49237bbf36045df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
